version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/usr/src/app/data
    environment:
      - RUST_LOG=debug
      - APP__DATABASE__URL=sqlite:///usr/src/app/data/tikpilot.db
      - APP__SERVER__HOST=0.0.0.0
      - APP__SERVER__PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8080
      - REMIX_DEV_ORIGIN=http://localhost:3000
      - PORT=3000
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

volumes:
  backend_data:
